#!/usr/bin/env python3
"""
NtupleForge CRAB Wrapper
=============================
This script runs on the worker node.
It prepares the environment and executes 'run_postproc.py'.
It robustly retrieves input files by reading the generated PSet.py.
"""

import os
import sys
import subprocess
import logging
import importlib.util

# Setup Logging
logging.basicConfig(level=logging.INFO, format='[crab_script] : %(message)s')
logger = logging.getLogger("Wrapper")

def get_input_files_from_pset():
    """
    Reads the input file list from the PSet.py file generated by CRAB.
    This is more reliable than relying on sys.argv in some splitting modes.
    """
    pset_path = "PSet.py"
    if not os.path.exists(pset_path):
        logger.error(f"{pset_path} not found!")
        return []

    try:
        # Dynamically load PSet.py as a module
        spec = importlib.util.spec_from_file_location("PSet", pset_path)
        pset = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(pset)
        
        # Extract the list of files from process.source.fileNames
        process = getattr(pset, "process", None)
        if process and hasattr(process, "source") and hasattr(process.source, "fileNames"):
            files = list(process.source.fileNames)
            logger.info(f"Extracted {len(files)} files from PSet.py")
            return files
        else:
            logger.error("Failed to extract fileNames from PSet.py")
            return []
    except Exception as e:
        logger.error(f"Error reading PSet.py: {e}")
        return []

def main():
    logger.info("="*60)
    logger.info(f"Wrapper Started on Host: {os.uname().nodename}")
    logger.info(f"Current Directory: {os.getcwd()}")
    logger.info("="*60)

    # ------------------------------------------------------------------
    # 1. Environment Setup
    # ------------------------------------------------------------------
    # CRAB flattens input files. We must add PWD to PYTHONPATH.
    cwd = os.getcwd()
    if "PYTHONPATH" in os.environ:
        os.environ["PYTHONPATH"] = f"{cwd}:{os.environ['PYTHONPATH']}"
    else:
        os.environ["PYTHONPATH"] = cwd

    # Also attempt to add 'script' directory if it exists (though usually flattened)
    if os.path.exists("script"):
        os.environ["PYTHONPATH"] = f"{cwd}/script:{os.environ['PYTHONPATH']}"

    logger.info(f"PYTHONPATH set to: {os.environ['PYTHONPATH']}")

    # ------------------------------------------------------------------
    # 2. Get Input Files
    # ------------------------------------------------------------------
    # Robustly retrieve input files from PSet.py
    input_files = get_input_files_from_pset()
    
    if not input_files:
        # Fallback: Check sys.argv if PSet extraction failed or was empty
        logger.warning("No files found in PSet.py, checking sys.argv...")
        for arg in sys.argv[2:]:
            if arg.endswith('.root'):
                input_files.append(arg)

    if not input_files:
        logger.error("CRITICAL: No input files found!")
        sys.exit(1)

    logger.info(f"Target Input Files: {input_files}")

    # ------------------------------------------------------------------
    # 3. Locate Main Script
    # ------------------------------------------------------------------
    script_name = "run_postproc.py"
    main_script = None

    if os.path.exists(script_name):
        main_script = script_name
        logger.info(f"Found main script in PWD: {main_script}")
    elif os.path.exists(f"script/{script_name}"):
        main_script = f"script/{script_name}"
        logger.info(f"Found main script in subfolder: {main_script}")
    else:
        logger.error(f"CRITICAL: {script_name} not found!")
        subprocess.run(["ls", "-R"])
        sys.exit(1)

    # ------------------------------------------------------------------
    # 4. Inject User Arguments
    # ------------------------------------------------------------------
    # We look for 'crab_args.txt' which contains flags like -b, -I, etc.
    args_file = "crab_args.txt"
    extra_flags = []

    if os.path.exists(args_file):
        logger.info(f"Loading arguments from {args_file}")
        try:
            with open(args_file, "r") as f:
                # Read lines, strip whitespace, and ignore empty lines
                for line in f:
                    clean_line = line.strip()
                    if clean_line:
                        extra_flags.append(clean_line)
        except Exception as e:
            logger.error(f"Failed to read args file: {e}")
            sys.exit(1)
            
    else:
        logger.warning(f"{args_file} not found. Running with defaults.")

    # ------------------------------------------------------------------
    # 5. Execution
    # ------------------------------------------------------------------
    # Construct command: python3 run_postproc.py [inputs] [flags]
    cmd = [sys.executable, main_script] + input_files + extra_flags
    
    logger.info("-" * 60)
    logger.info(f"Command: {' '.join(cmd)}")
    logger.info("-" * 60)

    try:
        # Flush buffers to ensure logs appear in order
        sys.stdout.flush()
        subprocess.run(cmd, check=True)
        logger.info("✅ Post-processing completed successfully.")
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ Execution failed with exit code {e.returncode}")
        # run_postproc.py --audit copies ROOT's stderr into forge_stderr.txt while
        # NanoAODTools copies and the audit reads (forge_audit.py; normally the
        # lines also reach stderr at once through tee). If the process died inside
        # that block the file is still here: print its first and last 20 lines and
        # every ROOT error line in it, at most 40 (2026-09-28).
        cap = "forge_stderr.txt"
        if os.path.exists(cap):
            try:
                import collections
                import re
                head, tail, errs, n = [], collections.deque(maxlen=20), [], 0
                with open(cap, "rb") as f:
                    for raw in f:
                        line = raw.decode("utf-8", "replace").rstrip("\n")
                        n += 1
                        if len(head) < 20:
                            head.append(line)
                        else:
                            tail.append(line)
                        if (line.startswith(("Error in <", "SysError in <", "Fatal in <")) and len(errs) < 40
                                and not re.match(r"Error in <TTree::SetBranchStatus>: (?:unknown branch|No branch "
                                                 r"name is matching wildcard) -> ", line)):
                            errs.append(line)   # a keep pattern matching nothing is not an error (C2w)
                logger.error("%s: %d line(s); first 20, ROOT error lines (%d shown), last 20:" % (cap, n, len(errs)))
                for line in head + ["  --- ROOT error lines ---"] + errs + ["  --- last lines ---"] + list(tail):
                    logger.error("  " + line)
            except OSError as ex:
                logger.error("cannot read %s: %s" % (cap, ex))
        # CRAB's wrapper takes the job's exit code from the first FrameworkError in
        # FrameworkJobReport.xml and uses this script's exit code only when there is
        # none (2024: an audit 85 arrived as 5, not retried; docs/05 A28). Since P7.1
        # run_postproc.py puts its FrameworkError there (fjr_mark_error); say which
        # code CRAB will see. The exit code stays non-zero: a report CRAB could not
        # read must not turn into a success.
        status = forge_fjr_error("FrameworkJobReport.xml")
        if status is not None:
            logger.error("FrameworkJobReport.xml carries FrameworkError ExitStatus=%s (run_postproc.py exit %d): "
                         "CRAB fails the job with %s" % (status, e.returncode, status))
        sys.exit(e.returncode)


def forge_fjr_error(path):
    """ExitStatus of the first FrameworkError in the report if run_postproc.py
    wrote it (Type="Forge..."), else None."""
    import re
    try:
        with open(path, "rb") as f:
            text = f.read().decode("utf-8", "replace")
    except OSError:
        return None
    m = re.search(r"<FrameworkError\b[^>]*>", text)
    if not m:
        return None
    tag = m.group(0)
    st = re.search(r'ExitStatus="(\d+)"', tag)
    if st and re.search(r'Type="Forge', tag):
        return int(st.group(1))
    return None

if __name__ == "__main__":
    main()
