common:
  jobID: campaign_ttHH2024_v15_had_Data_v1_pilot
  site: T3_KR_KNU
  output_base: ttHH2024_v15_had_Data_v1_pilot
  analysis_module:
  - modules/noop.py
  - MODULES
  branch_file: branches/branch_hadronic_2024_v15_Data.txt
  splitting: FileBased
  units_per_job: 1
datasets:
  JetMET0_Run2024H-MINIv6NANOv15-v2: /JetMET0/Run2024H-MINIv6NANOv15-v2/NANOAOD
